### PR TITLE
add support for multichain (residue_index) and real msa

### PR DESCRIPTION
**Pull request by sokrypton**

### CODE REVIEW

**Comment by pengzhangzhi** [comment]
interesting pr. Would you like to elaborate on what you have done?

**Comment by sokrypton** [comment]
See more details here:

For multichain modeling (w/ residue index hack):
https://twitter.com/sokrypton/status/1555114259209674752
For real msa:
https://twitter.com/sokrypton/status/1555142289873313794

In short, we can hack OmegaFold to predict protein-protein interactions and replace the pseudo-MSA with real MSA :)

**Comment by sokrypton** [comment]
I'm not sure if the residue index is correctly implemented for the sin/cos RoPE module...

Still investigating.

**Comment by pengzhangzhi** [comment]
Terrific! Have you compare the result of a single sequence and multiple pseudo MSA? Does pseudo MSA helps?

**Comment by RuiWang1998** [comment]
Hi @pengzhangzhi,

Dr. @sokrypton here have already contacted us about the performance of MSA-enhanced OmegaFold. You can checkout his recent tweets about it here: https://twitter.com/sokrypton. In the mean time, thanks so much for your volunteering help here. We really appreciate it!


Dr. @sokrypton, Sorry for the delay, we are quite busy here at HeliXon currently. We are going to review the pull request and merge it (hopefully) in no time!

Thank you both so much for contributing!

Best,
Rui

**Comment by sokrypton** [comment]
oops! looks like I accidentally deleted the branch while trying to merge latest commits from HeliXonProtein :D

**Comment by RuiWang1998** [comment]
Hi Dr @sokrypton,

Sorry for the delay, but we have updated OmegaFold with significantly reduced memory overhead and would very much like to go on with this pull request if this is okay with you?

Best

**Comment by sokrypton** [comment]
Hi Rui,
I'll work on merging the edits into GitHub. Seems lots of changes happened,
that I'm no longer able to just do an automated merge 😅

**Comment by RuiWang1998** [comment]
Hi Dr @sokrypton,

Great! We are sorry for the changes and delays. It is just that we think making the model accessible to more people is also very important.

Once you finish the edits, feel free to open a pull request!

Best

**Comment by JackMaguire** [comment]
@sokrypton is this PR still on your radar? If not, would you be willing to proofread an attempt if I give it a shot?

**Comment by sokrypton** [comment]
Sounds good!

**Pull request closed without merging**
