### PR TITLE
Make install easier and add `omegafold` command

### PR DESCRIPTION
**Pull request by hanjinliu**
This PR adds some features to make OmegaFold easier to use.

- Add setup.py so that users can install omegafold without cloning.
- Install `omegafold` command so that users don't have to move to the OmegaFold directory to run it.
- Support installation on Windows.

I appreciate if you consider these updates.

### CODE REVIEW

**Comment by RuiWang1998** [comment]
Great! Thanks for the suggestion. We have realized that macOS is not supported yet, so we would like to (hopefully) very quickly modify the underlying code a bit to support Apple M1 as well as installations. Maybe update a bit after that? We are looking at time frame within 24 hours.

**Comment by RuiWang1998** [comment]
Hi @hanjinliu,

Thanks for you contribution! This looks good to me right now.

However, it is a breaking change, meaning that it breaks the current behavior and the previous users might find it baffling. ColabFold, for example, has already implemented a notebook based on OmegaFold, and we would like to make sure that notebook updates alongside this pull request.

Also we think we have made some small modifications to allow the model to run on Apple Silicon, and wheels should be from https://download.pytorch.org/whl/nightly/torch/ for one of the macos ones, but we are not really familiar with the version (macos_10_9 vs macos_11_0?) yet, probably will look into that further.

**Comment by hanjinliu** [comment]
Hi @RuiWang1998 ,
Thanks for your review!
I tried not to break previous behaviors, but I'm sorry if there's something incompatible.
Unfortunately, I'm not familiar with running pytorch on MacOS either... hope you'll find a way to integrate that.

**Review by RuiWang1998 — APPROVED** [review]
LGTM, but this is a breaking change so let's let people know.

**Comment by RuiWang1998** [comment]
Hi Dr @sokrypton ,

We have updated the repo with PR #3 for easier install but it breaks the current behavior. So we would like to let you know s.t. you could update the ColabFold notebook accordingly.

Best

**Comment by RuiWang1998** [comment]
Sorry Scratch the above. I think this pull request works with old usage.

**Pull request merged**
