### PR TITLE
adding support for multichain modeling (with residue index modification) and input of real msa

### PR DESCRIPTION
**Pull request by sokrypton**

### CODE REVIEW

**Comment by RuiWang1998** [comment]
Hi,

Thanks for the suggestion! We will very soon review the code and merge the pull request (eta within 24 hours).

Best
Rui

**Comment by sokrypton** [comment]
This was just a quick hack from my side! If you guys want to do a more proper or leigt implementation of the same concept, feel free to close. I will not be offended. 😄

**Comment by RuiWang1998** [comment]
Thanks it looks great! We are going to look into it further and make the decision.

**Comment by sokrypton** [comment]
The one part I was not sure about is the sin/cos embedding and if that also needed to be offset in some way using the residue index?

**Comment by sokrypton** [comment]
for real MSA option, i wonder if it makes sense to unalign the sequences, pass full sequences to LM then realign the embeddings (or maybe provide a different residue index for each sequence? which would include info based on insertions/deletions)

**Comment by sokrypton** [comment]
oops accidently renamed branch. I'll submit a new pull request soon :D

**Pull request closed without merging**
